name: Build KernelSU For MI8(sirius)

on:
  workflow_dispatch:

jobs:
  KSUForSirius:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install git ccache automake flex lzop bison \
              gperf build-essential zip curl zlib1g-dev zlib1g-dev:i386 \
              g++-multilib python-networkx libxml2-utils bzip2 libbz2-dev \
              libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush \
              schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev \
              pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl \
              libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev \
              x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/SelectSex/Xiaomi_Kernel_OpenSource_mi_8 --depth=1 -b main --recurse-submodules android_kernel_xiaomi_8_android10
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002 --depth=1 --single-branch --no-tags -b 12.0 ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          git clone https://github.com/SakuraNotStupid/AnyKernel3
      - name: Compiling Kernel(AOSP)
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd android_kernel_xiaomi_8_android10
          make O="$output_dir" \
                      dipper_user_defconfig
          make -j $(nproc) \
                       O="$output_dir" \
                       CC=clang
          popd
      - name: Packaging the Kernel(AOSP)
        run: |
          rm -rf AnyKernel3/Image.gz
          cp -v android_kernel_xiaomi_8_android10/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../MI8_KernelSU_AOSP.zip *
          popd
      - name: Creating Config Info
        run: |
          echo "Device: MI 8
          Code: Sirius/Xmsirius
          Build Code: ${{ github.run_number }}
          KernelSU For MI8" >> INFO.txt
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: MI8SE_KernelSU_AOSP.zip
          name: "MI8_KernelSU"
          tag: " ${{ github.run_number }}_MI8_KernelSU"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
